  (Name:       'Arming Sword'; TypeOf: 0 ),
  (Name:      'Bastard Sword'; TypeOf: 0 ),
  (Name:         'Battle Axe'; TypeOf: 0 ),
  (Name:      'Bec de Corbin'; TypeOf: 0 ),
  (Name:               'Bill'; TypeOf: 0 ),
  (Name:         'Broadsword'; TypeOf: 0 ),
  (Name:               'Club'; TypeOf: 0 ),
  (Name:               'Dirk'; TypeOf: 0 ),
  (Name:           'Falchion'; TypeOf: 0 ),
  (Name:      'Footman's Axe'; TypeOf: 0 ),
  (Name:         'Giant Club'; TypeOf: 0 ),
  (Name:        'Giant Flail'; TypeOf: 0 ),
  (Name:        'Giant Sword'; TypeOf: 0 ),
  (Name:            'Gladius'; TypeOf: 0 ),
  (Name:             'Glaive'; TypeOf: 0 ),
  (Name:          'Great Axe'; TypeOf: 0 ),
  (Name:         'Greatsword'; TypeOf: 0 ),
  (Name:            'Halberd'; TypeOf: 0 ),
  (Name:           'Hand Axe'; TypeOf: 0 ),
  (Name:         'Heavy Club'; TypeOf: 0 ),
  (Name:        'Heavy Flail'; TypeOf: 0 ),
  (Name:         'Heavy Mace'; TypeOf: 0 ),
  (Name:     'Horseman's Axe'; TypeOf: 0 ),
  (Name:            'Javelin'; TypeOf: 0 ),
  (Name:        'Light Flail'; TypeOf: 0 ),
  (Name:         'Light Mace'; TypeOf: 0 ),
  (Name:          'Longsword'; TypeOf: 0 ),
  (Name:               'Maul'; TypeOf: 0 ),
  (Name:      'Military Pick'; TypeOf: 0 ),
  (Name:       'Morning Star'; TypeOf: 0 ),
  (Name:           'Partisan'; TypeOf: 0 ),
  (Name:               'Pike'; TypeOf: 0 ),
  (Name:            'Poleaxe'; TypeOf: 0 ),
  (Name:       'Quarterstaff'; TypeOf: 0 ),
  (Name:             'Rapier'; TypeOf: 0 ),
  (Name:             'Rondel'; TypeOf: 0 ),
  (Name:              'Sabre'; TypeOf: 0 ),
  (Name:         'Shortsword'; TypeOf: 0 ),
  (Name:             'Sickle'; TypeOf: 0 ),
  (Name:       'Single Stick'; TypeOf: 0 ),
  (Name:       'Sledgehammer'; TypeOf: 0 ),
  (Name:         'Smallsword'; TypeOf: 0 ),
  (Name:              'Spear'; TypeOf: 0 ),
  (Name:             'Spetum'; TypeOf: 0 ),
  (Name:       'Throwing Axe'; TypeOf: 0 ),
  (Name:            'Trident'; TypeOf: 0 ),
  (Name:               'Wand'; TypeOf: 0 ),
  (Name:          'Warhammer'; TypeOf: 0 ),
  (Name:     'Zweih\[:a]nder'; TypeOf: 0 ),
  (Name:         'Side-Sword'; TypeOf: 0 ),
